---
- name: "update apt packages."
  become: yes
  yum:
    update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   yum:
#     upgrade: yes
- name: "Install nodejs and npm"
  become: yes
  shell:  |
    curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -
    yum -y install nodejs
  # yum:
  #   name: ["nvm", "npm"]
  #   update_cache: yes
- name: "Install pm2"
  become: yes
  shell:  |
    npm i pm2 -g
  # yum:
  #   name: ["pm2"]
    # global: yes
    # production: yes
- name: "Create directory"
  file:
    path: ~/web
    state: directory
- name: "setup index.js file"
  copy: 
    src: index.js
    dest: ~/web/index.js
    backup: yes
- name: "start the webserver"
  become: yes
  shell: pm2 start ~/web/index.js -f
  # register: print_result
# - name: print message
#   debug:
#     msg: "{{ print_result.stdout_lines }}"
    